### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by shiva4983** [ejoebstl/proxy-login-automator-docker#1]
Hi @ejoebstl 

Could you please elaborate on the usage? how to reference with other container or application. Currently the proxy is exposed at http://localhost:[port]

**Comment by ejoebstl** [comment]
The question you ask is out of this scope for this project - That depends on your the container orchestration tool you use.

With docker, you would usually [create a virtual network for your containers instead](https://docs.docker.com/engine/reference/commandline/network_create/) of exposing a port at localhost. In practice, this is done by your container orchestration tool.
